version: "8.4.0"

services:
  mysqldb:
    platform: linux/arm64
    image: mysql:8.0
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=$MYSQL_DATABASE
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u root" ]
      interval: 30s
      timeout: 30s
      retries: 3

  app:
    depends_on:
      - mysqldb
    restart: on-failure
    image: posts-service
    build: .
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
      - $DEBUG_PORT:$DEBUG_PORT
    environment:
      SPRING_APPLICATION_JSON: '{"spring.datasource.url": "jdbc:mysql://mysqldb:$MYSQL_DOCKER_PORT/$MYSQL_DATABASE", "spring.datasource.username": "root", "spring.datasource.password": "", "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQLDialect"}'
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
